import {
  User,
  Project,
  Task,
  ActivityLog,
  Notification,
  DashboardStats,
  Client,
  Role,
  TaskStatus,
  TaskPriority,
} from '../types/index.js';

// Pre-seeded Users
export const mockUsers: User[] = [
  { id: 'usr-admin-1', email: 'admin@velozity.com', name: 'Aman Sharma', role: 'ADMIN' },
  { id: 'usr-pm-1', email: 'sarah.pm@velozity.com', name: 'Sarah Chen', role: 'PROJECT_MANAGER' },
  { id: 'usr-pm-2', email: 'marcus.pm@velozity.com', name: 'Marcus Vance', role: 'PROJECT_MANAGER' },
  { id: 'usr-dev-1', email: 'ravi.dev@velozity.com', name: 'Ravi Kumar', role: 'DEVELOPER' },
  { id: 'usr-dev-2', email: 'elena.dev@velozity.com', name: 'Elena Rostova', role: 'DEVELOPER' },
  { id: 'usr-dev-3', email: 'alex.dev@velozity.com', name: 'Alex Morgan', role: 'DEVELOPER' },
  { id: 'usr-dev-4', email: 'priya.dev@velozity.com', name: 'Priya Patel', role: 'DEVELOPER' },
];

export const mockClients: Client[] = [
  { id: 'cli-1', name: 'Apex Financial Holdings', company: 'Apex Financial Group', email: 'contact@apexfin.com' },
  { id: 'cli-2', name: 'BioPulse Therapeutics', company: 'BioPulse Health Inc.', email: 'team@biopulse.org' },
];

export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    title: 'Banking Core Modernization',
    description: 'Migrating legacy mainframe ledger workflows to high-throughput cloud event streaming architecture.',
    clientId: 'cli-1',
    pmId: 'usr-pm-1',
    client: mockClients[0],
    projectManager: mockUsers[1],
    createdAt: new Date(Date.now() - 30 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-2',
    title: 'Clinical Telemetry Portal',
    description: 'Real-time patient monitoring platform with HIPAA-compliant sensor streaming and alert dispatch.',
    clientId: 'cli-2',
    pmId: 'usr-pm-2',
    client: mockClients[1],
    projectManager: mockUsers[2],
    createdAt: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'proj-3',
    title: 'Real-Time Fraud Detection Engine',
    description: 'Sub-millisecond inference pipeline utilizing graph neural networks for anomalous transaction flagging.',
    clientId: 'cli-1',
    pmId: 'usr-pm-1',
    client: mockClients[0],
    projectManager: mockUsers[1],
    createdAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

const now = Date.now();
const day = 24 * 3600 * 1000;

export let mockTasks: Task[] = [
  // Project 1 Tasks
  {
    id: 'task-1',
    title: 'Design PostgreSQL Ledger Schema with Dual-Entry Audit',
    description: 'Implement immutable transaction logs with cryptographic hash chain checks.',
    projectId: 'proj-1',
    developerId: 'usr-dev-1',
    status: 'DONE',
    priority: 'CRITICAL',
    dueDate: new Date(now - 5 * day).toISOString(),
    isOverdue: false,
    project: mockProjects[0],
    assignedDeveloper: mockUsers[3],
    createdAt: new Date(now - 10 * day).toISOString(),
    updatedAt: new Date(now - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: 'task-2',
    title: 'Implement Kafka Event Ingestion Consumer',
    description: 'Build robust consumer group with dead-letter queue and retry backoff.',
    projectId: 'proj-1',
    developerId: 'usr-dev-1',
    status: 'IN_REVIEW',
    priority: 'HIGH',
    dueDate: new Date(now + 2 * day).toISOString(),
    isOverdue: false,
    project: mockProjects[0],
    assignedDeveloper: mockUsers[3],
    createdAt: new Date(now - 7 * day).toISOString(),
    updatedAt: new Date(now - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'task-3',
    title: 'Reconcile Multi-Currency Exchange Rates API',
    description: 'Connect to Bloomberg real-time FX feed with fallback cache.',
    projectId: 'proj-1',
    developerId: 'usr-dev-2',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    dueDate: new Date(now - 3 * day).toISOString(),
    isOverdue: true, // OVERDUE 1
    project: mockProjects[0],
    assignedDeveloper: mockUsers[4],
    createdAt: new Date(now - 6 * day).toISOString(),
    updatedAt: new Date(now - 1 * 3600 * 1000).toISOString(),
  },
  {
    id: 'task-4',
    title: 'Stress Test Ledger Locking Concurrency',
    description: 'Benchmark row-level lock contention under 10,000 requests/sec.',
    projectId: 'proj-1',
    developerId: 'usr-dev-2',
    status: 'TODO',
    priority: 'HIGH',
    dueDate: new Date(now + 5 * day).toISOString(),
    isOverdue: false,
    project: mockProjects[0],
    assignedDeveloper: mockUsers[4],
    createdAt: new Date(now - 5 * day).toISOString(),
    updatedAt: new Date(now - 5 * day).toISOString(),
  },
  {
    id: 'task-5',
    title: 'SOC2 Compliance Data Retention Policies',
    description: 'Configure automated S3 Glacier archival rules and PII anonymization.',
    projectId: 'proj-1',
    developerId: 'usr-dev-3',
    status: 'TODO',
    priority: 'LOW',
    dueDate: new Date(now + 10 * day).toISOString(),
    isOverdue: false,
    project: mockProjects[0],
    assignedDeveloper: mockUsers[5],
    createdAt: new Date(now - 4 * day).toISOString(),
    updatedAt: new Date(now - 4 * day).toISOString(),
  },
  {
    id: 'task-6',
    title: 'Audit Trail Export to CSV and PDF',
    description: 'Generate signed audit reports with HMAC verification.',
    projectId: 'proj-1',
    developerId: 'usr-dev-1',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    dueDate: new Date(now + 5 * day).toISOString(),
    isOverdue: false,
    project: mockProjects[0],
    assignedDeveloper: mockUsers[3],
    createdAt: new Date(now - 3 * day).toISOString(),
    updatedAt: new Date(now - 30 * 60 * 1000).toISOString(),
  },

  // Project 2 Tasks
  {
    id: 'task-7',
    title: 'ECG Signal WebSocket Streaming Server',
    description: 'Deliver 250Hz pulse telemetry with packet loss recovery.',
    projectId: 'proj-2',
    developerId: 'usr-dev-3',
    status: 'IN_PROGRESS',
    priority: 'CRITICAL',
    dueDate: new Date(now - 3 * day).toISOString(),
    isOverdue: true, // OVERDUE 2
    project: mockProjects[1],
    assignedDeveloper: mockUsers[5],
    createdAt: new Date(now - 8 * day).toISOString(),
    updatedAt: new Date(now - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-8',
    title: 'ICD-10 Diagnostic Code Mapping',
    description: 'Integrate standard medical vocabulary and fuzzy lookup endpoint.',
    projectId: 'proj-2',
    developerId: 'usr-dev-4',
    status: 'DONE',
    priority: 'MEDIUM',
    dueDate: new Date(now - 5 * day).toISOString(),
    isOverdue: false,
    project: mockProjects[1],
    assignedDeveloper: mockUsers[6],
    createdAt: new Date(now - 7 * day).toISOString(),
    updatedAt: new Date(now - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-9',
    title: 'Critical Vital Threshold Alert Push System',
    description: 'Dispatch immediate push notifications and SMS when vitals exceed safe ranges.',
    projectId: 'proj-2',
    developerId: 'usr-dev-3',
    status: 'IN_REVIEW',
    priority: 'CRITICAL',
    dueDate: new Date(now + 2 * day).toISOString(),
    isOverdue: false,
    project: mockProjects[1],
    assignedDeveloper: mockUsers[5],
    createdAt: new Date(now - 6 * day).toISOString(),
    updatedAt: new Date(now - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-10',
    title: 'Biometric Wearable Bluetooth Pair Flow',
    description: 'Mobile web WebBluetooth API bridge for pulse oximeter pairing.',
    projectId: 'proj-2',
    developerId: 'usr-dev-4',
    status: 'TODO',
    priority: 'HIGH',
    dueDate: new Date(now + 5 * day).toISOString(),
    isOverdue: false,
    project: mockProjects[1],
    assignedDeveloper: mockUsers[6],
    createdAt: new Date(now - 5 * day).toISOString(),
    updatedAt: new Date(now - 5 * day).toISOString(),
  },
  {
    id: 'task-11',
    title: 'Nurse Station Multi-Bed Overview Grid',
    description: 'Responsive telemetry grid rendering 16 simultaneous patient waveforms.',
    projectId: 'proj-2',
    developerId: 'usr-dev-4',
    status: 'TODO',
    priority: 'HIGH',
    dueDate: new Date(now + 10 * day).toISOString(),
    isOverdue: false,
    project: mockProjects[1],
    assignedDeveloper: mockUsers[6],
    createdAt: new Date(now - 4 * day).toISOString(),
    updatedAt: new Date(now - 4 * day).toISOString(),
  },

  // Project 3 Tasks
  {
    id: 'task-12',
    title: 'Train Graph Convolutional Network on Anomaly Dataset',
    description: 'Evaluate PyTorch Geometric model performance with ROC-AUC metric.',
    projectId: 'proj-3',
    developerId: 'usr-dev-1',
    status: 'DONE',
    priority: 'HIGH',
    dueDate: new Date(now - 5 * day).toISOString(),
    isOverdue: false,
    project: mockProjects[2],
    assignedDeveloper: mockUsers[3],
    createdAt: new Date(now - 9 * day).toISOString(),
    updatedAt: new Date(now - 15 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-13',
    title: 'ONNX Runtime Model Quantization',
    description: 'Quantize FP32 model to INT8 to achieve under 5ms inference latency.',
    projectId: 'proj-3',
    developerId: 'usr-dev-2',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: new Date(now + 2 * day).toISOString(),
    isOverdue: false,
    project: mockProjects[2],
    assignedDeveloper: mockUsers[4],
    createdAt: new Date(now - 6 * day).toISOString(),
    updatedAt: new Date(now - 10 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-14',
    title: 'Rule-Based Safety Override Heuristics',
    description: 'Hard constraints for sanctioned jurisdictions and velocity checks.',
    projectId: 'proj-3',
    developerId: 'usr-dev-2',
    status: 'IN_REVIEW',
    priority: 'CRITICAL',
    dueDate: new Date(now + 5 * day).toISOString(),
    isOverdue: false,
    project: mockProjects[2],
    assignedDeveloper: mockUsers[4],
    createdAt: new Date(now - 5 * day).toISOString(),
    updatedAt: new Date(now - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'task-15',
    title: 'Risk Score Dashboard Component',
    description: 'Color-coded radial gauge displaying transaction risk percentage.',
    projectId: 'proj-3',
    developerId: 'usr-dev-1',
    status: 'TODO',
    priority: 'MEDIUM',
    dueDate: new Date(now + 10 * day).toISOString(),
    isOverdue: false,
    project: mockProjects[2],
    assignedDeveloper: mockUsers[3],
    createdAt: new Date(now - 4 * day).toISOString(),
    updatedAt: new Date(now - 4 * day).toISOString(),
  },
  {
    id: 'task-16',
    title: 'Webhook Callback Notification Service',
    description: 'Deliver asynchronous fraud risk alerts to merchant checkout APIs.',
    projectId: 'proj-3',
    developerId: 'usr-dev-3',
    status: 'TODO',
    priority: 'LOW',
    dueDate: new Date(now + 10 * day).toISOString(),
    isOverdue: false,
    project: mockProjects[2],
    assignedDeveloper: mockUsers[5],
    createdAt: new Date(now - 3 * day).toISOString(),
    updatedAt: new Date(now - 3 * day).toISOString(),
  },
];

export let mockActivities: ActivityLog[] = [
  {
    id: 'act-1',
    projectId: 'proj-1',
    taskId: 'task-1',
    userId: 'usr-dev-1',
    actionText: 'Ravi Kumar moved Task "Design PostgreSQL Ledger Schema with Dual-Entry Audit" from In Review → Done',
    createdAt: new Date(now - 4 * 3600 * 1000).toISOString(),
    user: mockUsers[3],
    project: mockProjects[0],
  },
  {
    id: 'act-2',
    projectId: 'proj-1',
    taskId: 'task-2',
    userId: 'usr-dev-1',
    actionText: 'Ravi Kumar moved Task "Implement Kafka Event Ingestion Consumer" from In Progress → In Review',
    createdAt: new Date(now - 2 * 3600 * 1000).toISOString(),
    user: mockUsers[3],
    project: mockProjects[0],
  },
  {
    id: 'act-3',
    projectId: 'proj-1',
    taskId: 'task-3',
    userId: 'usr-pm-1',
    actionText: 'Sarah Chen assigned Task "Reconcile Multi-Currency Exchange Rates API" to Elena Rostova',
    createdAt: new Date(now - 1 * 3600 * 1000).toISOString(),
    user: mockUsers[1],
    project: mockProjects[0],
  },
  {
    id: 'act-4',
    projectId: 'proj-2',
    taskId: 'task-8',
    userId: 'usr-dev-4',
    actionText: 'Priya Patel moved Task "ICD-10 Diagnostic Code Mapping" from In Review → Done',
    createdAt: new Date(now - 45 * 60 * 1000).toISOString(),
    user: mockUsers[6],
    project: mockProjects[1],
  },
  {
    id: 'act-5',
    projectId: 'proj-2',
    taskId: 'task-9',
    userId: 'usr-dev-3',
    actionText: 'Alex Morgan moved Task "Critical Vital Threshold Alert Push System" from In Progress → In Review',
    createdAt: new Date(now - 25 * 60 * 1000).toISOString(),
    user: mockUsers[5],
    project: mockProjects[1],
  },
  {
    id: 'act-6',
    projectId: 'proj-3',
    taskId: 'task-12',
    userId: 'usr-dev-1',
    actionText: 'Ravi Kumar moved Task "Train Graph Convolutional Network on Anomaly Dataset" from In Progress → Done',
    createdAt: new Date(now - 15 * 60 * 1000).toISOString(),
    user: mockUsers[3],
    project: mockProjects[2],
  },
  {
    id: 'act-7',
    projectId: 'proj-3',
    taskId: 'task-14',
    userId: 'usr-dev-2',
    actionText: 'Elena Rostova moved Task "Rule-Based Safety Override Heuristics" from In Progress → In Review',
    createdAt: new Date(now - 5 * 60 * 1000).toISOString(),
    user: mockUsers[4],
    project: mockProjects[2],
  },
];

export let mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: 'usr-dev-1',
    message: 'You have been assigned to task: "Audit Trail Export to CSV and PDF"',
    isRead: false,
    createdAt: new Date(now - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'usr-pm-1',
    message: 'Task "Implement Kafka Event Ingestion Consumer" was submitted for In Review by Ravi Kumar',
    isRead: false,
    createdAt: new Date(now - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'usr-pm-2',
    message: 'Task "Critical Vital Threshold Alert Push System" was submitted for In Review by Alex Morgan',
    isRead: false,
    createdAt: new Date(now - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif-4',
    userId: 'usr-dev-2',
    message: 'You have been assigned to task: "Reconcile Multi-Currency Exchange Rates API"',
    isRead: true,
    createdAt: new Date(now - 1 * 3600 * 1000).toISOString(),
  },
];

// In-memory session tracking
let currentMockUser: User | null = mockUsers[0]; // defaults to Admin

export const setMockUser = (user: User | null) => {
  currentMockUser = user;
};

export const getMockUser = () => currentMockUser;

export const dispatchMockEvent = (eventName: string, detail: any) => {
  window.dispatchEvent(new CustomEvent(eventName, { detail }));
};
